version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3007:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3006:3000"
